NCKU資安新秀/dinosaur/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
#from schedule.views import CalendarView 
from django.urls import path
from.import views

app_name = 'dinosaur'

urlpatterns = [
   # path('calendar/', CalendarView.as_view(), name='calendar'),
    #re_path(r'^$', views.list, name='list'),#列出所有會議室
    re_path(r'^$', views.logi, name='logi'),#列出所有會議室
    re_path(r'^list', views.list, name='list'),#列出所有會議室
    re_path(r'^(?P<id>[0-9]+)/$', views.appointment, name='appointment'),#列出預約情況
    #re_path(r'^logi/$', views.logi, name='logi'),
    re_path(r'^logo/$', views.logo, name='logo'),
    re_path(r'^register/$', views.register, name='register'),
    re_path(r'^(?P<id>[0-9]+)/add/$', views.add, name='add'),
    re_path(r'^(?P<room_id>[0-9]+)/(?P<order_id>[0-9]+)/delete/$', views.delete, name='delete'),
]

#TEST
# urlpatterns = [
#     path('',views.index,name='index'),
# ]
# urlpatterns = [
#     path('', views.showtemplate),
# ]

NCKU資安新秀/meeting/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path as url
from django.conf.urls import include
from django.contrib import admin
from rest_framework.routers import DefaultRouter
from dinosaur import views


router = DefaultRouter()
router.register(r'check', views.GroupViewSet)




# urlpatterns = [
#     path('meeting/', include('dinosaur.urls')),
#     path('admin/', admin.site.urls),
#     url(r'^api/', include(router.urls)),
#     #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
#     url(r'^api/update/', views.update_checkdig, name='update_checkdig'),
# ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 

#Local
urlpatterns = [
    path('', include('dinosaur.urls')),
    path('admin/', admin.site.urls),
    url(r'^api/', include(router.urls)),
    #url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/update/', views.update_checkdig, name='update_checkdig'),
    url(r'^api/updateisempty/', views.update_isempty, name='update_isempty'),
] 

NCKU資安新秀/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    
    <!-- 這個meta不要動 -->
    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self'; child-src 'none'; form-action 'self';">
    <!-- 這個meta不要動 -->

    <!-- Bootstrap core CSS -->
    {% load static %}
    <!-- <base href="/"> -->
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}" type="text/css" /> -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'css/mycss.css' %}" type="text/css"/>
    <!-- <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" /> -->

</head>

    <body>
        <!-- <div class="container-fluid bg-dark py-2 d-none d-md-flex"> -->
        <div class="container-fluid bg-custom text-white py-2 d-none d-md-flex">
            <a class="navbar-brand text-white" href="{% url 'dinosaur:list' %}">NCKU-GSS</a>
            <div class="container">

            </div>
            {% if request.user.is_active %}
            <p class="navbar-text">{{ user.username }}/<a href="{% url 'dinosaur:logo' %}"  class="text-white">Logout</a> </p>
            {% else %}
            <p class="navbar-text"><a href="{% url 'dinosaur:register' %}" class="text-white">Register</a>/<a href="{% url 'dinosaur:logi' %}" class="text-white">Login</a></p>
            {% endif %}
        </div>
    
    
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>
        <!--     <script src="{% static 'js/npm.js' %}"></script> -->
        {% if messages %}
        <ul class="messagelist">
            {% for i in messages %}
                <li>{{ i }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        
        <div class="row justify-content-center mt-3">
            <div class="col-sm-8 col-lg-8 offset-lg-1">
                {% block body %}{% endblock %}
            </div>
        </div>

</html>

NCKU資安新秀/templates/calendar.html
<!DOCTYPE html>
<html>
<head>
    <title>会议室日历</title>
    <link href='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.css' rel='stylesheet' />
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.10.2/fullcalendar.min.js'></script>
    <script>
        $(document).ready(function () {
            $('#calendar').fullCalendar({
                events: '/calendar_data/',
                defaultView: 'agendaWeek', // 使用 agendaWeek 视图以显示1小时的时间间隔
                slotDuration: '01:00:00', // 设置时间间隔为1小时
                editable: true,
                eventResize: function (event, delta, revertFunc) {
                    alert("Event end time changed!");
                }
            });
        });
    </script>
</head>
<body>
    <h1>会议室预约日历</h1>
    <div id='calendar'></div>
</body>
</html>

NCKU資安新秀/templates/list.html
{% extends 'base.html' %}

{% block title %}會議室列表{% endblock %}
{% include 'calendar.html' %}
{% block body %}
<!-- <h1>會議室列表：</h1> -->
    {% for i in room %}
<h3><a href="{% url 'dinosaur:appointment' i.id %}">{{i.room_status}}{{ i.num }}({{i.size}})</a></h3>
    {% endfor %}
{% endblock %}

NCKU資安新秀/templates/logi.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {% if request.path == '/' %}
        登入
    {% elif 'register' in request.path %}
        註冊
    {% elif 'add' in request.path %}
        登記
    {% else %}
        Default Title
    {% endif %}
{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'css/mycss.css' %}" type="text/css">
{% endblock %}

{% block body %}
    <div class="center-form">
        <div class="top-text">
            {% if request.path == '/' %}
                <p>登入</p>
            {% elif 'register' in request.path %}
                <p>註冊</p>
            {% elif 'add' in request.path %}
                <p>登記</p>
            {% endif %}
        </div>
        <div class="form-box">
            <form method="POST" action="">
                {% csrf_token %}
                {{ form.as_p }}
                <button class="login100-form-btn" type="submit">
                    {% if request.path == '/' %}
                        Login
                    {% elif 'register' in request.path %}
                        Register
                    {% elif 'add' in request.path %}
                        Book
                    {% endif %}
                </button>
            </form>
        </div>
    </div>
    <div class="center-form">
    <img src="{% static 'activate.jpg' %}" alt="Your Image" class="top-image">
    </div>
{% endblock %}

NCKU資安新秀/templates/order.html
{% extends 'base.html' %}

{% block title %}預約詳情 | {{ room.num }}{% endblock %}

{% block body %}
<table class="table table-bordered">
    <tr>
        <td>開始時間</td>
        <td>結束時間</td>
        <td>預約人</td>
        <td>會議室</td>
        <td>簽到狀態</td>
        <td>操作</td>
    </tr>
    {% for i in order %}
    <tr>
        <td>{{ i.start_time }}</td>
        <td>{{ i.end_time }}</td>
        <td>{{ i.user }}</td>
        <td>{{ i.room }}</td>
        <td>{{ i.checkdig }}</td>
        <td>
            {% if i.user == request.user %}
            <a href="{% url 'dinosaur:delete' room.id i.id %}">取消</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
</table>

<br>
<a href="{% url 'dinosaur:add' room.id %}" class="btn btn-default" role="button">預約</a>
<p>*一次預約一小時喔*</p>
{% endblock %}

NCKU資安新秀/templates/test.html
<!-- <!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <h1> Hey there, u can see me! </h1>
  </body>
</html> -->




<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self'; child-src 'none'; form-action 'self';">

    

    <!-- Bootstrap core CSS -->
    {% load static %}
    <!-- <base href="/"> -->
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}" type="text/css" /> -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css"/>
    <!-- <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" /> -->

</head>


<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navtop">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'dinosaur:list' %}">Home</a>
            </div>

            <div class="collapse navbar-collapse" id="navtop">

                <ul class="nav navbar-nav navbar-right">
                    <!--<li><a href="#">New blog</a></li>-->
                    <li>
                        {% if request.user.is_active %}
                        <p class="navbar-text">{{ user.username }}/<a href="{% url 'dinosaur:logo' %}">Logout</a> </p>
                        {% else %}
                        <p class="navbar-text"><a href="{% url 'dinosaur:register' %}">Register</a>/<a href="{% url 'dinosaur:logi' %}">Login</a></p>
                        {% endif %}
                    </li>
                </ul>

            </div>

        </div>
    </nav>


    {% if messages %}
    <ul class="messagelist">
        {% for i in messages %}
        <li>{{ i }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="row">
        <div class="col-sm-8 col-lg-offset-1">
            {% block body %}{% endblock %}
        </div>
    </div>

 

    <!-- footer -->
    <footer class="footer" role="contentinfo">
        <hr>
        <div class="container">
            <!-- <p class="text-center">Copyright © Zhenhua Liao</p>
            <h5 class="text-center"> Thanks For Bootstrap </h5> -->
        </div>
    </footer>
    <!-- /.footer-->



    <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>
    <!--     <script src="{% static 'js/npm.js' %}"></script> -->



</body>
</html> -->









<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>

    <meta http-equiv="Content-Security-Policy" content="default-src 'self'; img-src 'self'; child-src 'none'; form-action 'self';">

    

    <!-- Bootstrap core CSS -->
    {% load static %}
    <!-- <base href="/"> -->
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}" type="text/css" /> -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css"/>
    <!-- <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" /> -->

</head>

    <body>
        <!-- Spinner Start -->
        <!-- <div id="spinner" class="show position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-grow text-primary" role="status"></div>
        </div> -->
        <!-- Spinner End -->

        <!-- Topbar Start -->
        <div class="container-fluid bg-dark py-2 d-none d-md-flex">
            <div class="container">
                <a class="navbar-brand" href="{% url 'dinosaur:list' %}">Home</a>
                <div class="d-flex justify-content-between topbar">
                    <!-- <div class="top-info">
                        <small class="me-3 text-white-50"><a href="#"><i class="fas fa-map-marker-alt me-2 text-secondary"></i></a>23 Ranking Street, New York</small>
                        <small class="me-3 text-white-50"><a href="#"><i class="fas fa-envelope me-2 text-secondary"></i></a>Email@Example.com</small>
                    </div>
                    <div id="note" class="text-secondary d-none d-xl-flex"><small>Note : We help you to Grow your Business</small></div> -->
                    <div class="top-link">
                        <a href="" class="bg-light nav-fill btn btn-sm-square rounded-circle"><i class="fab fa-facebook-f text-primary"></i></a>
                        <a href="" class="bg-light nav-fill btn btn-sm-square rounded-circle"><i class="fab fa-instagram text-primary"></i></a>
                    </div>
                </div>
            </div>
            {% if request.user.is_active %}
            <p class="navbar-text">{{ user.username }}/<a href="{% url 'dinosaur:logo' %}">Logout</a> </p>
            {% else %}
            <p class="navbar-text"><a href="{% url 'dinosaur:register' %}">Register</a>/<a href="{% url 'dinosaur:logi' %}">Login</a></p>
            {% endif %}
        </div>
    
    
        <script src="{% static 'jquery/jquery.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>
        <!--     <script src="{% static 'js/npm.js' %}"></script> -->
        {% if messages %}
        <ul class="messagelist">
            {% for i in messages %}
                <li>{{ i }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        
        <div class="row justify-content-center mt-3">
            <div class="col-sm-8 col-lg-8 offset-lg-1">
                {% block body %}{% endblock %}
            </div>
        </div>

</html>

NCKU資安新秀/templates/timetable.html
<!DOCTYPE html>
<html>
<head>
    <title>课表</title>
    <style>
        table {
            border-collapse: collapse;
            width: 100%;
        }

        th, td {
            border: 1px solid #ddd;
            text-align: center;
            padding: 8px;
        }

        th {
            background-color: #f2f2f2;
        }

        tr:nth-child(even) {
            background-color: #f2f2f2;
        }
    </style>
</head>
<body>
    <h1>课表</h1>
    <table>
        <tr>
            <th>时间</th>
            <!-- 根据您的需求添加日期列 -->
            {% for date in dates %}
            <th>{{ date }}</th>
            {% endfor %}
        </tr>
        {% for time in time_range %}
        <tr>
            <td>{{ time }}</td>
            {% for date in dates %}
            <td>
                {% for appointment in appointments %}
                {% if appointment.date == date and appointment.start_time <= time and appointment.end_time > time %}
                已预约
                {% endif %}
                {% endfor %}
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
    </table>
</body>
</html>